### ISSUE TITLE
Clickable (linking) toplevel navbar links with dropdowns

### ISSUE THREAD

**Issue by bassscape** [arnabwahid/wordpress-bootstrap#62]
I would like to change the standard Bootstrap navbar menu behaviours. Instead of a toplevel link just triggering a dropdown menu when it has secondlevel menu item I would like it to also link to a page.

I have achieved this behaviour with WordPress using the Roots Theme but I can't get it using 320press WordPress Bootstrap.

Here's the css I used to make dropdowns appear on hover and retain clickable/working links on the parent menu item:

``` css
/* This rule makes toplevel menu items clickable links and also displays dropdown menus on hover - WHOA! */
ul.nav li.dropdown:hover ul.dropdown-menu { display: block; margin:0;}
a.menu:after, .dropdown-toggle:after { content: none; }
```

Additionally the following code from this comment on GitHub also worked for the same behaviours:
https://github.com/retlehs/roots/issues/269#issuecomment-4708273

``` javascript
$(document).ready(
  function () {
    $('nav > ul > li:has(ul) > a').attr('href', function (i, val) { return val + '#'; });
  }
);
```

Neither of these bits of code seem to work for me in 320press WordPress Bootstrap. Could anyone advise why they may not be working or how to get this code working?
